apiVersion: v2
publisher: hellofalks
name: hellofalks
version: 0.0.1
type: VS Code extension
displayName: helloFalks
title: helloFalks
description: my plugin for hello
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository:
category:
spec:
  containers:
    - image: quay.io/eclipse/che-plugin-sidecar@sha256:70836fd2fc01198c1a31f44d0af9cdf2d7445035be54f0bc7ae2cbfe262e0231
      name: vscode-java
      memoryLimit: 1500Mi
  extensions:
          - https://github.com/william-xiang/vs-extension/raw/main/helloFalks.vsix